hostname: zhangjg.github.io
permalink: /:categories/:year-:month-:day-:title.html
markdown: redcarpet
encoding: "utf-8"
source: [_post/2015,_post/2016]
paginate: 20
paginate_path: "/archive/page:num/"

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            categories: blog
            layout: "default"
            author: "Zhangjg"
